# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('espresso_shots', models.PositiveIntegerField(default=1)),
                ('water', models.FloatField(default=100)),
                ('steamed_milk', models.BooleanField(default=False)),
                ('foam', models.FloatField(default=2)),
                ('extra_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Action',
            new_name='Bean',
        ),
        migrations.RenameModel(
            old_name='Name',
            new_name='Powder',
        ),
        migrations.RenameModel(
            old_name='Set',
            new_name='Roast',
        ),
        migrations.RenameModel(
            old_name='Color',
            new_name='Syrup',
        ),
        migrations.AddField(
            model_name='coffee',
            name='bean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Bean'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='powder',
            field=models.ManyToManyField(blank=True, to='game.Powder'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='roast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Roast'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='syrup',
            field=models.ManyToManyField(blank=True, to='game.Syrup'),
        ),
    ]
